// Generated by Sterling SDK Generator — test suite
// Task Manager API v0.2.0

import { TaskmanagerSdkClient } from "../src/client";
import { APIError, NotFoundError, BadRequestError, InternalServerError } from "../src/errors";

// ── Fetch mock ──────────────────────────────────────────────────────────

interface CapturedRequest {
  url: string;
  method: string;
  body: string | null;
}

let captured: CapturedRequest | null = null;
let mockStatus = 200;
let mockBody: unknown = {};
const origFetch = globalThis.fetch;

(globalThis as any).fetch = async (_input: string | URL | Request, init?: RequestInit): Promise<Response> => {
  const url = typeof _input === "string" ? _input : _input instanceof URL ? _input.toString() : (_input as Request).url;
  captured = {
    url,
    method: (init?.method ?? "GET").toUpperCase(),
    body: init?.body ? String(init.body) : null,
  };
  return new Response(JSON.stringify(mockBody), {
    status: mockStatus,
    headers: { "content-type": "application/json" },
  });
};

function reset(status = 200, body: unknown = {}): void {
  captured = null;
  mockStatus = status;
  mockBody = body;
}

function ok(cond: boolean, msg: string): void {
  if (!cond) throw new Error(msg);
}

function makeClient(): TaskmanagerSdkClient {
  return new TaskmanagerSdkClient({ baseUrl: "http://localhost:9999", apiKey: "test-key", maxRetries: 0 });
}

// ── Operation tests ─────────────────────────────────────────────────────

async function test_list_tasks(): Promise<void> {
  reset();
  const c = makeClient();
  await c.listTasks();
  ok(captured !== null, "list_tasks: request captured");
  ok(captured!.method === "GET", "list_tasks: expected GET, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "list_tasks: url prefix");
}

async function test_create_task(): Promise<void> {
  reset();
  const c = makeClient();
  await c.createTask({} as any);
  ok(captured !== null, "create_task: request captured");
  ok(captured!.method === "POST", "create_task: expected POST, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "create_task: url prefix");
  ok(captured!.body !== null, "create_task: body sent");
}

async function test_get_task(): Promise<void> {
  reset();
  const c = makeClient();
  await c.getTask("test-id");
  ok(captured !== null, "get_task: request captured");
  ok(captured!.method === "GET", "get_task: expected GET, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "get_task: url prefix");
}

async function test_delete_task(): Promise<void> {
  reset();
  const c = makeClient();
  await c.deleteTask("test-id");
  ok(captured !== null, "delete_task: request captured");
  ok(captured!.method === "DELETE", "delete_task: expected DELETE, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "delete_task: url prefix");
}

async function test_update_task(): Promise<void> {
  reset();
  const c = makeClient();
  await c.updateTask("test-id", {} as any);
  ok(captured !== null, "update_task: request captured");
  ok(captured!.method === "PATCH", "update_task: expected PATCH, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "update_task: url prefix");
  ok(captured!.body !== null, "update_task: body sent");
}

async function test_complete_task(): Promise<void> {
  reset();
  const c = makeClient();
  await c.completeTask("test-id", {} as any);
  ok(captured !== null, "complete_task: request captured");
  ok(captured!.method === "POST", "complete_task: expected POST, got " + captured!.method);
  ok(captured!.url.startsWith("http://localhost:9999/"), "complete_task: url prefix");
  ok(captured!.body !== null, "complete_task: body sent");
}

// ── Error handling tests ────────────────────────────────────────────────

async function testErrors(): Promise<void> {
  const c = makeClient();

  reset(400, { message: "bad request" });
  try { await c.listTasks(); ok(false, "should throw"); } catch (e: unknown) {
    ok(e instanceof BadRequestError, "400 → BadRequestError");
  }

  reset(404, { message: "not found" });
  try { await c.listTasks(); ok(false, "should throw"); } catch (e: unknown) {
    ok(e instanceof NotFoundError, "404 → NotFoundError");
  }

  reset(500, { message: "server error" });
  try { await c.listTasks(); ok(false, "should throw"); } catch (e: unknown) {
    ok(e instanceof InternalServerError, "500 → InternalServerError");
  }
}

// ── Runner ──────────────────────────────────────────────────────────────

async function main(): Promise<void> {
  let passed = 0;
  let failed = 0;

  const tests: Array<[string, () => Promise<void>]> = [
    ["list_tasks", test_list_tasks],
    ["create_task", test_create_task],
    ["get_task", test_get_task],
    ["delete_task", test_delete_task],
    ["update_task", test_update_task],
    ["complete_task", test_complete_task],
    ["error_handling", testErrors],
  ];

  for (const [name, fn] of tests) {
    try {
      await fn();
      passed++;
      console.log(`  ✓ ${name}`);
    } catch (e) {
      failed++;
      console.error(`  ✗ ${name}: ${(e as Error).message}`);
    }
  }

  globalThis.fetch = origFetch;
  console.log(`\n${passed} passed, ${failed} failed`);
  if (failed > 0) process.exit(1);
}

main();
