// Generated by Sterling SDK Generator
// Task Manager API v0.2.0

/**
 * A subclass of `Promise` providing additional helper methods
 * for interacting with the SDK.
 */
export class APIPromise<T> extends Promise<T> {
  private parsedPromise: Promise<T> | undefined;

  private constructor(
    private responsePromise: Promise<Response>,
    private parseResponse: (response: Response) => Promise<T>,
  ) {
    super((resolve) => {
      // no-op: resolution is deferred to .then/.catch/.finally
      resolve(null as any);
    });
  }

  /**
   * Creates an APIPromise that parses the response body as JSON.
   */
  static fromResponse<T>(responsePromise: Promise<Response>): APIPromise<T> {
    return new APIPromise<T>(responsePromise, async (response) => response.json() as Promise<T>);
  }

  /**
   * Creates an APIPromise that returns the raw Response.
   */
  static fromRawResponse(responsePromise: Promise<Response>): APIPromise<Response> {
    return new APIPromise<Response>(responsePromise, async (response) => response);
  }

  /**
   * Gets the parsed response data and the raw `Response` instance.
   */
  async withResponse(): Promise<{ data: T; response: Response }> {
    const response = await this.responsePromise;
    const data = await this.parseResponse(response);
    return { data, response };
  }

  /**
   * Gets the raw `Response` instance without parsing the body.
   */
  asResponse(): Promise<Response> {
    return this.responsePromise;
  }

  private parse(): Promise<T> {
    if (!this.parsedPromise) {
      this.parsedPromise = this.responsePromise.then((response) => this.parseResponse(response));
    }
    return this.parsedPromise;
  }

  override then<TResult1 = T, TResult2 = never>(
    onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null,
    onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null,
  ): Promise<TResult1 | TResult2> {
    return this.parse().then(onfulfilled, onrejected);
  }

  override catch<TResult = never>(
    onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null,
  ): Promise<T | TResult> {
    return this.parse().catch(onrejected);
  }

  override finally(onfinally?: (() => void) | undefined | null): Promise<T> {
    return this.parse().finally(onfinally);
  }
}
