// Generated by Sterling SDK Generator
// Task Manager API v0.2.0

import type { Task, TaskListResponse, ErrorResponse, CreateTaskRequest, UpdateTaskRequest, ListTasksParams,  } from "./models";
import type { RequestOptions } from "./request-options";
import { APIError, APIConnectionError } from "./errors";
import { getEnv, detectRuntime, getDefaultFetch } from "./shims";

export interface Logger {
  error(message: string, ...args: unknown[]): void;
  warn(message: string, ...args: unknown[]): void;
  info(message: string, ...args: unknown[]): void;
  debug(message: string, ...args: unknown[]): void;
}

export type LogLevel = 'debug' | 'info' | 'warn' | 'error' | 'off';

const LOG_LEVEL_ORDER: Record<LogLevel, number> = {
  off: 0,
  error: 1,
  warn: 2,
  info: 3,
  debug: 4,
};

function parseLogLevel(value: string | undefined): LogLevel | undefined {
  if (value && value in LOG_LEVEL_ORDER) return value as LogLevel;
  return undefined;
}

export interface TaskmanagerSdkClientOptions {
  baseUrl?: string;
  apiKey?: string;
  headers?: Record<string, string | null>;
  /** Maximum number of retries on 5xx/network errors. Default: 2 */
  maxRetries?: number;
  /** Request timeout in milliseconds. Default: 30000 */
  timeout?: number;
  /** Log level. Defaults to VERS_LOG env var or 'warn'. */
  logLevel?: LogLevel;
  /** Custom fetch implementation for testing, proxying, or custom transport. */
  fetch?: typeof fetch;
  /** Additional options to pass to every underlying `fetch` call (e.g. dispatcher, keepalive). */
  fetchOptions?: RequestInit;
  /** Custom logger (compatible with pino, winston, bunyan, consola, etc.). Default: console */
  logger?: Logger;
}

// Status codes that are retryable even though they are 4xx
const RETRYABLE_STATUS_CODES = new Set([408, 409, 429]);

function isRetryableStatus(status: number): boolean {
  return status >= 500 || RETRYABLE_STATUS_CODES.has(status);
}

function retryDelay(retryCount: number): number {
  const base = 500 * Math.pow(2, retryCount);
  const jitter = Math.random() * base * 0.25;
  return base + jitter;
}

function parseRetryAfter(headerValue: string | null): number | null {
  if (headerValue == null) return null;
  const seconds = Number(headerValue);
  if (!Number.isNaN(seconds)) {
    return Math.min(Math.max(seconds * 1000, 0), 60000);
  }
  const date = new Date(headerValue);
  if (!Number.isNaN(date.getTime())) {
    const delayMs = date.getTime() - Date.now();
    return Math.min(Math.max(delayMs, 0), 60000);
  }
  return null;
}

export class TaskmanagerSdkClient {
  private baseUrl: string;
  private apiKey?: string;
  private headers: Record<string, string | null>;
  private maxRetries: number;
  private timeout: number;
  private logLevel: LogLevel;
  private fetchFn: typeof fetch;
  private fetchOptions: RequestInit;
  private logger: Logger;

  // Resource accessors

  constructor(options: TaskmanagerSdkClientOptions = {}) {
    this.baseUrl = options.baseUrl ?? getEnv("VERS_BASE_URL") ?? "http://localhost:8080";
    this.apiKey = options.apiKey ?? getEnv("VERS_API_KEY");
    this.headers = options.headers ?? {};
    this.maxRetries = options.maxRetries ?? 2;
    this.timeout = options.timeout ?? 30000;
    this.logLevel = options.logLevel ?? parseLogLevel(getEnv("VERS_LOG")) ?? 'warn';
    this.fetchFn = options.fetch ?? globalThis.fetch;
    this.fetchOptions = options.fetchOptions ?? {};
    this.logger = options.logger ?? console;

    // Initialize resources
  }

  /**
   * Make a GET request to an arbitrary path. Uses the same authentication,
   * retries, and error handling as generated methods.
   */
  get<T = unknown>(path: string, options?: RequestOptions): Promise<T> {
    return this.request("GET", path, undefined, options).then(r => r.json() as Promise<T>);
  }

  /**
   * Make a POST request to an arbitrary path.
   */
  post<T = unknown>(path: string, body?: unknown, options?: RequestOptions): Promise<T> {
    return this.request("POST", path, body, options).then(r => r.json() as Promise<T>);
  }

  /**
   * Make a PUT request to an arbitrary path.
   */
  put<T = unknown>(path: string, body?: unknown, options?: RequestOptions): Promise<T> {
    return this.request("PUT", path, body, options).then(r => r.json() as Promise<T>);
  }

  /**
   * Make a PATCH request to an arbitrary path.
   */
  patch<T = unknown>(path: string, body?: unknown, options?: RequestOptions): Promise<T> {
    return this.request("PATCH", path, body, options).then(r => r.json() as Promise<T>);
  }

  /**
   * Make a DELETE request to an arbitrary path.
   */
  del<T = unknown>(path: string, options?: RequestOptions): Promise<T> {
    return this.request("DELETE", path, undefined, options).then(r => r.json() as Promise<T>);
  }

  private log(level: LogLevel, message: string): void {
    if (level === 'off' || LOG_LEVEL_ORDER[level] > LOG_LEVEL_ORDER[this.logLevel]) return;
    const ts = new Date().toISOString();
    const tag = `[vers_sdk]`;
    const msg = `${ts} ${tag} ${message}`;
    this.logger[level](msg);
  }

  private mergeHeaders(...sources: (Record<string, string | null | undefined> | undefined)[]): Record<string, string> {
    const merged: Record<string, string> = {};
    for (const source of sources) {
      if (!source) continue;
      for (const [key, value] of Object.entries(source)) {
        if (value === null || value === undefined) {
          // Remove header (case-insensitive)
          for (const k of Object.keys(merged)) {
            if (k.toLowerCase() === key.toLowerCase()) delete merged[k];
          }
        } else {
          merged[key] = value;
        }
      }
    }
    return merged;
  }

  private get userAgent(): string {
    const runtime = detectRuntime();
    let rt: string;
    switch (runtime) {
      case "deno":
        rt = `deno/${(globalThis as any).Deno?.version?.deno ?? "unknown"}`;
        break;
      case "bun":
        rt = `bun/${(globalThis as any).Bun?.version ?? "unknown"}`;
        break;
      case "node":
        rt = `node/${process.versions?.node ?? "unknown"}`;
        break;
      case "edge":
        rt = "edge-runtime";
        break;
      case "browser":
        rt = "browser";
        break;
      default:
        rt = "unknown-runtime";
    }
    const os = typeof process !== "undefined"
      ? `${process.platform ?? "unknown"}/${process.arch ?? "unknown"}`
      : "unknown-os";
    return `taskmanager-sdk/0.2.0 ${rt} ${os}`;
  }

  private async request(method: string, path: string, body?: unknown, options?: RequestOptions): Promise<Response> {
    const defaultHeaders: Record<string, string> = {
      "Content-Type": "application/json",
      "User-Agent": this.userAgent,
    };
    if (this.apiKey) {
      defaultHeaders["Authorization"] = `Bearer ${this.apiKey}`;
    }
    const headers = this.mergeHeaders(defaultHeaders, this.headers, options?.headers);

    const mutating = ["POST", "PUT", "PATCH", "DELETE"].includes(method.toUpperCase());
    if (mutating) {
      headers["X-Idempotency-Key"] = crypto.randomUUID();
    }
    // Merge per-request headers; null values remove the header
    if (options?.headers) {
      for (const [key, value] of Object.entries(options.headers)) {
        if (value === null) {
          delete headers[key];
        } else {
          headers[key] = value;
        }
      }
    }

    const effectiveTimeout = options?.timeout ?? this.timeout;

    this.log('debug', `request: ${method} ${path}`);
    let lastError: unknown;
    let lastRetryAfterUsed = false;
    for (let attempt = 0; attempt <= this.maxRetries; attempt++) {
      if (attempt > 0 && !lastRetryAfterUsed) {
        this.log('info', `retry attempt ${attempt}/${this.maxRetries} for ${method} ${path}`);
        await new Promise((resolve) => setTimeout(resolve, retryDelay(attempt - 1)));
      }
      lastRetryAfterUsed = false;

      const controller = new AbortController();
      const timeoutId = setTimeout(() => controller.abort(), effectiveTimeout);
      // If caller provided an AbortSignal, forward its abort to our controller
      if (options?.signal) {
        if (options.signal.aborted) {
          controller.abort();
        } else {
          options.signal.addEventListener("abort", () => controller.abort(), { once: true });
        }
      }

      try {
        const mergedFetchOptions = { ...this.fetchOptions, ...options?.fetchOptions };
        const response = await this.fetchFn(`${this.baseUrl}${path}`, {
          ...mergedFetchOptions,
          method,
          headers,
          body: body ? JSON.stringify(body) : undefined,
          signal: controller.signal,
        });

        if (isRetryableStatus(response.status) && attempt < this.maxRetries) {
          const retryAfterDelay = parseRetryAfter(response.headers.get('retry-after'));
          if (retryAfterDelay != null) {
            lastRetryAfterUsed = true;
            this.log('info', `retry attempt ${attempt + 1}/${this.maxRetries} for ${method} ${path} (retry-after: ${retryAfterDelay}ms)`);
            await new Promise((resolve) => setTimeout(resolve, retryAfterDelay));
          }
          lastError = new Error(`HTTP ${response.status}`);
          continue;
        }

        this.log('debug', `response: ${response.status} for ${method} ${path}`);

        if (!response.ok) {
          let errorBody: object | undefined;
          let errorMessage: string | undefined;
          try {
            const text = await response.text();
            const ct = response.headers.get("content-type") ?? "";
            if (ct.includes("application/json")) {
              try { errorBody = JSON.parse(text); } catch { errorMessage = text; }
            } else {
              errorMessage = text;
            }
          } catch {}
          const err = APIError.generate(response.status, errorBody, errorMessage, response.headers);
          this.log('error', `API error: ${response.status} ${method} ${path}`);
          throw err;
        }

        return response;
      } catch (error) {
        if (error instanceof APIError) throw error;
        lastError = error;
        this.log('error', `connection error: ${method} ${path} - ${error instanceof Error ? error.message : String(error)}`);
        if (attempt === this.maxRetries) {
          throw new APIConnectionError({ cause: error instanceof Error ? error : undefined });
        }
      } finally {
        clearTimeout(timeoutId);
      }
    }

    throw lastError;
  }

  // ── Flat methods (also accessible via resource accessors) ─────────

  /**
   * List all tasks
   */
  async listTasks(params?: ListTasksParams, options?: RequestOptions): Promise<TaskListResponse> {
    let url = "/api/tasks";
    const searchParams = new URLSearchParams();
    if (params?.status !== undefined) searchParams.append("status", String(params.status));
    if (params?.limit !== undefined) searchParams.append("limit", String(params.limit));
    const qs = searchParams.toString();
    if (qs) url += "?" + qs;
    const resp = await this.request("GET", url, undefined, options);
    const text = await resp.text();
    if (!text) return {} as unknown as TaskListResponse;
    return JSON.parse(text) as TaskListResponse;
  }

  /**
   * Create a new task
   */
  async createTask(body: CreateTaskRequest, options?: RequestOptions): Promise<Task> {
    let url = "/api/tasks";
    const resp = await this.request("POST", url, body, options);
    const text = await resp.text();
    if (!text) return {} as unknown as Task;
    return JSON.parse(text) as Task;
  }

  /**
   * Get a task by ID
   */
  async getTask(task_id: string, options?: RequestOptions): Promise<Task> {
    let url = `/api/tasks/${task_id}`;
    const resp = await this.request("GET", url, undefined, options);
    const text = await resp.text();
    if (!text) return {} as unknown as Task;
    return JSON.parse(text) as Task;
  }

  /**
   * Delete a task
   */
  async deleteTask(task_id: string, options?: RequestOptions): Promise<any> {
    let url = `/api/tasks/${task_id}`;
    const resp = await this.request("DELETE", url, undefined, options);
    const text = await resp.text();
    if (!text) return {};
    return JSON.parse(text);
  }

  /**
   * Update a task
   */
  async updateTask(task_id: string, body: UpdateTaskRequest, options?: RequestOptions): Promise<Task> {
    let url = `/api/tasks/${task_id}`;
    const resp = await this.request("PATCH", url, body, options);
    const text = await resp.text();
    if (!text) return {} as unknown as Task;
    return JSON.parse(text) as Task;
  }

  /**
   * Mark a task as done
   */
  async completeTask(task_id: string, body: Record<string, unknown>, options?: RequestOptions): Promise<Task> {
    let url = `/api/tasks/${task_id}/complete`;
    const resp = await this.request("POST", url, body, options);
    const text = await resp.text();
    if (!text) return {} as unknown as Task;
    return JSON.parse(text) as Task;
  }
}
