// Generated by Sterling SDK Generator
// Task Manager API v0.2.0

/**
 * Base error class for the TaskmanagerSdk SDK.
 */
export class VersSDKError extends Error {
  constructor(message?: string) {
    super(message);
    this.name = "VersSDKError";
  }
}

/**
 * Error returned when the API responds with a non-success status code.
 */
export class APIError<
  TStatus extends number | undefined = number | undefined,
  THeaders extends Headers | undefined = Headers | undefined,
  TError extends object | undefined = object | undefined,
> extends VersSDKError {
  /** HTTP status code for the response that caused the error */
  readonly status: TStatus;
  /** HTTP headers for the response that caused the error */
  readonly headers: THeaders;
  /** Parsed JSON body of the error response */
  readonly error: TError;

  constructor(status: TStatus, error: TError, message: string | undefined, headers: THeaders) {
    super(APIError.makeMessage(status, error, message));
    this.name = "APIError";
    this.status = status;
    this.headers = headers;
    this.error = error;
  }

  /**
   * Extract the human-readable error message from the response.
   *
   * Looks for an `error` or `message` field in the JSON error body,
   * or falls back to the raw error text.
   */
  get errorMessage(): string {
    const e = this.error as Record<string, any> | undefined;
    if (e?.error && typeof e.error === "string") return e.error;
    if (e?.message && typeof e.message === "string") return e.message;
    return this.message;
  }

  private static makeMessage(status: number | undefined, error: any, message: string | undefined): string {
    const msg =
      error?.message
        ? typeof error.message === "string"
          ? error.message
          : JSON.stringify(error.message)
        : error
          ? JSON.stringify(error)
          : message;

    if (status && msg) {
      return `${status} ${msg}`;
    }
    if (status) {
      return `${status} status code (no body)`;
    }
    if (msg) {
      return msg;
    }
    return "(no status code or body)";
  }

  static generate(
    status: number | undefined,
    errorResponse: object | undefined,
    message: string | undefined,
    headers: Headers | undefined,
  ): APIError {
    if (!status || !headers) {
      return new APIConnectionError({ message, cause: errorResponse instanceof Error ? errorResponse : undefined });
    }

    const error = errorResponse as Record<string, any>;

    if (status === 400) return new BadRequestError(status, error, message, headers);
    if (status === 401) return new AuthenticationError(status, error, message, headers);
    if (status === 403) return new PermissionDeniedError(status, error, message, headers);
    if (status === 404) return new NotFoundError(status, error, message, headers);
    if (status === 409) return new ConflictError(status, error, message, headers);
    if (status === 422) return new UnprocessableEntityError(status, error, message, headers);
    if (status === 429) return new RateLimitError(status, error, message, headers);
    if (status >= 500) return new InternalServerError(status, error, message, headers);

    return new APIError(status, error, message, headers);
  }
}

/**
 * Error thrown when a connection to the API cannot be established.
 */
export class APIConnectionError extends APIError<undefined, undefined, undefined> {
  constructor({ message, cause }: { message?: string | undefined; cause?: Error | undefined } = {}) {
    super(undefined, undefined, message || "Connection error.", undefined);
    this.name = "APIConnectionError";
    if (cause) (this as any).cause = cause;
  }
}

/**
 * Error thrown when a request times out.
 */
export class APIConnectionTimeoutError extends APIConnectionError {
  constructor({ message }: { message?: string } = {}) {
    super({ message: message ?? "Request timed out." });
    this.name = "APIConnectionTimeoutError";
  }
}

export class BadRequestError extends APIError<400, Headers> {
  constructor(status: 400, error: object | undefined, message: string | undefined, headers: Headers) {
    super(status, error, message, headers);
    this.name = "BadRequestError";
  }
}

export class AuthenticationError extends APIError<401, Headers> {
  constructor(status: 401, error: object | undefined, message: string | undefined, headers: Headers) {
    super(status, error, message, headers);
    this.name = "AuthenticationError";
  }
}

export class PermissionDeniedError extends APIError<403, Headers> {
  constructor(status: 403, error: object | undefined, message: string | undefined, headers: Headers) {
    super(status, error, message, headers);
    this.name = "PermissionDeniedError";
  }
}

export class NotFoundError extends APIError<404, Headers> {
  constructor(status: 404, error: object | undefined, message: string | undefined, headers: Headers) {
    super(status, error, message, headers);
    this.name = "NotFoundError";
  }
}

export class ConflictError extends APIError<409, Headers> {
  constructor(status: 409, error: object | undefined, message: string | undefined, headers: Headers) {
    super(status, error, message, headers);
    this.name = "ConflictError";
  }
}

export class UnprocessableEntityError extends APIError<422, Headers> {
  constructor(status: 422, error: object | undefined, message: string | undefined, headers: Headers) {
    super(status, error, message, headers);
    this.name = "UnprocessableEntityError";
  }
}

export class RateLimitError extends APIError<429, Headers> {
  constructor(status: 429, error: object | undefined, message: string | undefined, headers: Headers) {
    super(status, error, message, headers);
    this.name = "RateLimitError";
  }
}

export class InternalServerError extends APIError<number, Headers> {
  constructor(status: number, error: object | undefined, message: string | undefined, headers: Headers) {
    super(status, error, message, headers);
    this.name = "InternalServerError";
  }
}
