// Generated by Sterling SDK Generator
// Task Manager API v0.2.0

export interface Task {
  id: string;
  title: string;
  description?: string;
  status: string;
  priority: number;
  created_at: string;
  updated_at: string;
  due_date?: string;
}

export interface TaskListResponse {
  tasks: Task[];
  total: number;
}

export interface ErrorResponse {
  /** Human-readable error message */
  error: string;
  /** Always false for errors */
  success: boolean;
}

export interface CreateTaskRequest {
  /** Task title (required) */
  title: string;
  /** Optional description */
  description?: string;
  /** Priority (0 = default) */
  priority?: number;
  due_date?: string;
}

export interface UpdateTaskRequest {
  title?: string;
  description?: string;
  status?: string;
  priority?: number;
  due_date?: string;
}


// ── Params types for operations with query parameters ───────────────

export interface ListTasksParams {
  /** Filter by task status */
  status?: string;
  /** Maximum number of tasks to return */
  limit?: number;
}

