// Generated by Sterling SDK Generator
// Task Manager API v0.2.0

/**
 * Per-request options that override client defaults.
 */
export interface RequestOptions {
  /**
   * Additional headers to send with the request.
   * Set a header to `null` to remove it from the request.
   */
  headers?: Record<string, string | null>;

  /**
   * Request timeout in milliseconds. Overrides the client-level timeout.
   */
  timeout?: number;

  /**
   * An AbortSignal to cancel the request.
   */
  signal?: AbortSignal | null;

  /**
   * Additional options to pass to the underlying `fetch` call.
   * These are merged on top of client-level fetchOptions.
   */
  fetchOptions?: RequestInit;
}
