// Generated by Sterling SDK Generator
// Cross-platform shims for Node.js, Deno, Bun, and edge runtimes

export const getDefaultFetch = (): typeof fetch => {
  if (typeof globalThis.fetch !== "undefined") return globalThis.fetch;
  throw new Error("No fetch implementation found. Pass a custom fetch to the client options.");
};

export const getEnv = (key: string): string | undefined => {
  // Node.js
  if (typeof process !== "undefined" && process.env) return process.env[key];
  // Deno
  if (typeof globalThis !== "undefined" && "Deno" in globalThis) {
    try { return (globalThis as any).Deno.env.get(key); } catch { return undefined; }
  }
  return undefined;
};

export const getDefaultTimeout = (): number => 30000;

export type Runtime = "node" | "deno" | "bun" | "edge" | "browser" | "unknown";

export const detectRuntime = (): Runtime => {
  if (typeof globalThis !== "undefined" && "Bun" in globalThis) return "bun";
  if (typeof globalThis !== "undefined" && "Deno" in globalThis) return "deno";
  if (typeof EdgeRuntime !== "undefined") return "edge";
  if (typeof process !== "undefined" && process.versions?.node) return "node";
  if (typeof window !== "undefined") return "browser";
  return "unknown";
};

declare const EdgeRuntime: string | undefined;
